//priority: 100

ServerEvents.tags(
    'item',
    tags => {
        
        //adding a Tag circuit_parts to items
        let parts = [
            'gtceu:resin_circuit_board',
            'gtceu:phenolic_circuit_board',
            'gtceu:plastic_circuit_board',
            'gtceu:epoxy_circuit_board',
            'gtceu:fiber_reinforced_circuit_board',
            'gtceu:multilayer_fiber_reinforced_circuit_board',
            'gtceu:wetware_circuit_board',
            'gtceu:resin_printed_circuit_board',
            'gtceu:phenolic_printed_circuit_board',
            'gtceu:plastic_printed_circuit_board',
            'gtceu:epoxy_printed_circuit_board',
            'gtceu:fiber_reinforced_printed_circuit_board',
            'gtceu:multilayer_fiber_reinforced_printed_circuit_board',
            'gtceu:wetware_printed_circuit_board',
            'gtceu:silicon_wafer',
            'gtceu:phosphorus_wafer',
            'gtceu:naquadah_wafer',
            'gtceu:neutronium_wafer',
            'gtceu:ilc_wafer',
            'gtceu:nano_cpu_wafer',
            'gtceu:qbit_cpu_wafer',
            'gtceu:simple_soc_wafer',
            'gtceu:soc_wafer',
            'gtceu:advanced_soc_wafer',
            'gtceu:highly_advanced_soc_wafer',
            'gtceu:ulpic_wafer',
            'gtceu:lpic_wafer',
            'gtceu:mpic_wafer',
            'gtceu:hpic_wafer',
            'gtceu:uhpic_wafer',
            'gtceu:engraved_crystal_chip',
            'gtceu:ilc_chip',
            'ae2:printed_calculation_processor',
            'ae2:printed_engineering_processor',
            'ae2:printed_logic_processor',
            'projectred_core:plate',
            'gtceu:transistor',
            'gtceu:resistor',
            'gtceu:capacitor',
            'gtceu:diode',
            'gtceu:smd_transistor',
            'gtceu:smd_resistor',
            'gtceu:smd_capacitor',
            'gtceu:smd_diode',
            'gtceu:smd_inductor',
            'gtceu:advanced_smd_transistor',
            'gtceu:advanced_smd_resistor',
            'gtceu:advanced_smd_capacitor',
            'gtceu:advanced_smd_diode',
            'gtceu:advanced_smd_inductor',
            'ae2:printed_silicon',
            'gtceu:engraved_lapotron_crystal_chip',
            'gtceu:cpu_chip',
            'gtceu:ram_chip',
            'gtceu:ilc_chip',
            'gtceu:nano_cpu_chip',
            'gtceu:qbit_cpu_chip',
            'gtceu:simple_soc',
            'gtceu:soc',
            'gtceu:advanced_soc',
            'gtceu:highly_advanced_soc',
            'gtceu:nand_memory_chip',
            'gtceu:nor_memory_chip',
            'gtceu:ulpic_chip',
            'gtceu:lpic_chip',
            'gtceu:mpic_chip',
            'gtceu:hpic_chip',
            'gtceu:uhpic_chip',
            'gtceu:raw_crystal_chip',
            'gtceu:raw_crystal_chip_parts',
            'gtceu:crystal_cpu',
            'gtceu:crystal_soc',
            'gtceu:transistor'
        ];
        tags.add('forge:circuit_parts', parts);

        //Making a plants tag for all plants
        let plants = [
            'minecraft:oak_leaves',
            'minecraft:spruce_leaves',
            'minecraft:birch_leaves',
            'minecraft:jungle_leaves',
            'minecraft:acacia_leaves',
            'minecraft:dark_oak_leaves',
            'minecraft:mangrove_leaves',
            'minecraft:cherry_leaves',
            'minecraft:azalea_leaves',
            'minecraft:flowering_azalea_leaves',
            'phantasm:pream_leaves',
            'mythicbotany:dreamwood_leaves',
            'quark:ancient_leaves',
            'quark:blue_blossom_leaves',
            'quark:lavender_blossom_leaves',
            'quark:orange_blossom_leaves',
            'quark:yellow_blossom_leaves',
            'quark:red_blossom_leaves',
            'twilightforest:twilight_oak_leaves',
            'twilightforest:canopy_leaves',
            'twilightforest:mangrove_leaves',
            'twilightforest:dark_leaves',
            'twilightforest:time_leaves',
            'twilightforest:mining_leaves',
            'twilightforest:transformation_leaves',
            'twilightforest:sorting_leaves',
            'twilightforest:rainbow_oak_leaves',
            'twilightforest:fallen_leaves',
            'twilightforest:beanstalk_leaves',
            'twilightforest:thorn_leaves',
            'twilightforest:giant_leaves',
            'wizards_reborn:arcane_wood_leaves',
            'wizards_reborn:innocent_wood_leaves',
            'forbidden_arcanus:aurum_leaves',
            'forbidden_arcanus:nuggety_aurum_leaves',
            'gtceu:rubber_leaves',
            
            'minecraft:oak_sapling',
            'minecraft:spruce_sapling',
            'minecraft:birch_sapling',
            'minecraft:jungle_sapling',
            'minecraft:acacia_sapling',
            'minecraft:dark_oak_sapling',
            'minecraft:mangrove_propagule',
            'minecraft:cherry_sapling',
            'phantasm:pream_sapling',
            'minecraft:azalea',
            'minecraft:flowering_azalea',
            'quark:ancient_sapling',
            'quark:blue_blossom_sapling',
            'quark:lavender_blossom_sapling',
            'quark:orange_blossom_sapling',
            'quark:yellow_blossom_sapling',
            'quark:red_blossom_sapling',
            'twilightforest:twilight_oak_sapling',
            'twilightforest:canopy_sapling',
            'twilightforest:mangrove_sapling',
            'twilightforest:darkwood_sapling',
            'twilightforest:time_sapling',
            'twilightforest:transformation_sapling',
            'twilightforest:mining_sapling',
            'twilightforest:sorting_sapling',
            'twilightforest:rainbow_oak_sapling',
            'twilightforest:hollow_oak_sapling',
            'wizards_reborn:arcane_wood_sapling',
            'wizards_reborn:innocent_wood_sapling',
            'forbidden_arcanus:aurum_sapling',
            'gtceu:rubber_sapling',

            'minecraft:brown_mushroom',
            'minecraft:red_mushroom',
            'minecraft:crimson_fungus',
            'minecraft:warped_fungus',
            'minecraft:fern',
            'minecraft:dead_bush',
            'minecraft:dandelion',
            'minecraft:poppy',
            'minecraft:blue_orchid',
            'minecraft:allium',
            'minecraft:azure_bluet',
            'minecraft:red_tulip',
            'minecraft:orange_tulip',
            'minecraft:white_tulip',
            'minecraft:pink_tulip',
            'minecraft:oxeye_daisy',
            'minecraft:cornflower',
            'minecraft:lily_of_the_valley',
            'minecraft:torchflower',
            'minecraft:wither_rose',
            'minecraft:pink_petals',
            'minecraft:bamboo',
            'minecraft:cactus',
            'minecraft:crimson_roots',
            'minecraft:warped_roots',
            'minecraft:twisting_vines',
            'minecraft:sunflower',
            'minecraft:lilac',
            'minecraft:rose_bush',
            'minecraft:peony',
            'minecraft:pitcher_plant',
            'minecraft:big_dripleaf',
            'minecraft:small_dripleaf',
            'minecraft:pitcher_pod',
            'minecraft:sweet_berries',
            'botania:white_mystical_flower',

            'botania:orange_shiny_flower',
            'botania:magenta_shiny_flower',
            'botania:light_blue_shiny_flower',
            'botania:yellow_shiny_flower',
            'botania:lime_shiny_flower',
            'botania:pink_shiny_flower',
            'botania:gray_shiny_flower',
            'botania:light_gray_shiny_flower',
            'botania:cyan_shiny_flower',
            'botania:purple_shiny_flower',
            'botania:blue_shiny_flower',
            'botania:green_shiny_flower',
            'botania:brown_shiny_flower',
            'botania:red_shiny_flower',
            'botania:black_shiny_flower',
            'botania:white_mushroom',
            'botania:orange_mushroom',
            'botania:magenta_mushroom',
            'botania:light_blue_mushroom',
            'botania:yellow_mushroom',
            'botania:lime_mushroom',
            'botania:pink_mushroom',
            'botania:gray_mushroom',
            'botania:light_gray_mushroom',
            'botania:cyan_mushroom',
            'botania:purple_mushroom',
            'botania:blue_mushroom',
            'botania:brown_mushroom',
            'botania:green_mushroom',
            'botania:red_mushroom',
            'botania:black_mushroom',
            'botania:white_double_flower',
            'botania:orange_double_flower',
            'botania:magenta_double_flower',
            'botania:light_blue_double_flower',
            'botania:yellow_double_flower',

            'botania:lime_double_flower',
            'botania:pink_double_flower',
            'botania:gray_double_flower',
            'botania:light_gray_double_flower',
            'botania:cyan_double_flower',
            'botania:purple_double_flower',
            'botania:blue_double_flower',
            'botania:brown_double_flower',
            'botania:green_double_flower',
            'botania:red_double_flower',
            'botania:black_double_flower',
            'phantasm:vivid_nihilis',
            'phantasm:pream_sapling',
            'phantasm:crystalily',
            'phantasm:starflower',
            'farmersdelight:wild_cabbages',
            'farmersdelight:wild_onions',
            'farmersdelight:wild_tomatoes',
            'farmersdelight:wild_carrots',
            'farmersdelight:wild_potatoes',
            'farmersdelight:wild_beetroots',
            'farmersdelight:wild_rice',
            'farmersdelight:brown_mushroom_colony',
            'farmersdelight:red_mushroom_colony',
            'immersive_weathering:azalea_leaf_pile',
            'immersive_weathering:flowering_azalea_leaf_pile',
            'immersive_weathering:azalea_flower_pile',
            'immersive_weathering:flower_crown',
            'immersive_weathering:azalea_flowers',
            'manyideas_core:flower_straight_allium',
            'manyideas_core:flower_straight_orchid_blue',
            'manyideas_core:flower_tall_straight_lilac',
            'manyideas_core:flower_tall_straight_peony',
            'manyideas_core:flower_tall_straight_rose_bush',
            'manyideas_core:flower_tall_straight_sunflower',

            'quark:oak_hedge',
            'quark:spruce_hedge',
            'quark:birch_hedge',
            'quark:jungle_hedge',
            'quark:acacia_hedge',
            'quark:dark_oak_hedge',
            'quark:mangrove_hedge',
            'quark:cherry_hedge',
            'quark:azalea_hedge',
            'quark:flowering_azalea_hedge',
            'quark:blue_blossom_hedge',
            'quark:lavender_blossom_hedge',
            'quark:orange_blossom_hedge',
            'quark:yellow_blossom_hedge',
            'quark:red_blossom_hedge',
            'quark:ancient_hedge',
            'quark:ancient_sapling',
            'quark:glow_shroom',
            'supplementaries:wild_flax',
            'supplementaries:flax_seeds',
            'twilightforest:thorn_rose',
            'wizards_reborn:petals_of_innocence',
            'wizards_reborn:mor',
            'wizards_reborn:elder_mor',
            'wizards_reborn:shiny_clover',
            'forbidden_arcanus:fungyss',
            'forbidden_arcanus:nipa',
            'forbidden_arcanus:yellow_orchid',
            'iceandfire:fire_lily',
            'iceandfire:frost_lily',
            'iceandfire:lightning_lily',

            'minecraft:grass',
            'minecraft:wheat_seeds',
            'minecraft:beetroot_seeds',
            'minecraft:torchflower_seeds',
            'minecraft:glow_berries',
            'minecraft:kelp',
            'minecraft:tube_coral',
            'minecraft:brain_coral',
            'minecraft:bubble_coral',
            'minecraft:fire_coral',
            'minecraft:horn_coral',
            'minecraft:carrot',
            'minecraft:potato',
            'farmersdelight:sandy_shrub',
            'farmersdelight:wild_beetroots',
            'farmersdelight:onion',
            'farmersdelight:rice_panicle',
            'farmersdelight:cabbage_seeds',
            'farmersdelight:tomato_seeds',
            'farmersdelight:rotten_tomato',
            'farmersdelight:pumpkin_slice',
            'immersive_weathering:frosty_grass',
            'immersive_weathering:frosty_fern',
            'supplementaries:flax_seeds',
            'twilightforest:mayapple',
            'twilightforest:clover_patch',
            'twilightforest:fiddlehead',
            'twilightforest:mushgloom',
            'twilightforest:torchberry_plant',
            'twilightforest:root_strand',
            'twilightforest:trollvidr',
            'twilightforest:unripe_trollber',
            'twilightforest:trollber',
            'twilightforest:huge_stalk',
            'twilightforest:huge_water_lily',

            'twilightforest:huge_water_lily',
            'twilightforest:huge_lily_pad',
            'twilightforest:thorn_rose',
            'twilightforest:hedge',
            'twilightforest:torchberries',
            'twilightforest:liveroot',
            'twilightforest:magic_beans',
            'wizards_reborn:cork_bamboo_seed',
            'wizards_reborn:cork_bamboo',
            'forbidden_arcanus:golden_orchid_seeds',
            'wizards_reborn:arcane_linen_seeds',
            'minecraft:cocoa_beans',
            'minecraft:pumpkin_seeds',
            'minecraft:melon_seeds',
            'botania:orange_mystical_flower ',
            'botania:magenta_mystical_flower ',
            'botania:light_blue_mystical_flower ',
            'botania:yellow_mystical_flower ',
            'botania:lime_mystical_flower ',
            'botania:pink_mystical_flower ',
            'botania:gray_mystical_flower ',
            'botania:light_gray_mystical_flower ',
            'botania:cyan_mystical_flower ',
            'botania:purple_mystical_flower ',
            'botania:blue_mystical_flower ',
            'botania:brown_mystical_flower ',
            'botania:green_mystical_flower ',
            'botania:red_mystical_flower ',
            'botania:black_mystical_flower ',
            'botania:white_shiny_flower ',
            'botania:white_floating_flower ',
            'botania:orange_floating_flower ',
            'botania:magenta_floating_flower ',
            'botania:light_blue_floating_flower ',
            'botania:yellow_floating_flower ',
            'botania:lime_floating_flower ',
            'botania:pink_floating_flower ',
            'botania:gray_floating_flower ',
            'botania:light_gray_floating_flower ',
            'botania:cyan_floating_flower ',
            'botania:purple_floating_flower ',
            'minecraft:moss_block ',
            'botania:blue_floating_flower ',
            'botania:green_floating_flower ',
            'botania:brown_floating_flower ',
            'botania:red_floating_flower ',
            'botania:black_floating_flower ',
            'minecraft:moss_carpet ',
            'minecraft:mangrove_roots ',
            'minecraft:vine',
            'minecraft:brown_mushroom_block ',
            'minecraft:red_mushroom_block ',
            'minecraft:nether_wart_block ',
            'minecraft:warped_wart_block ',
            'minecraft:shroomlight ',
            'minecraft:spore_blossom ',
            'minecraft:sugar_cane ',
            'minecraft:nether_sprouts ',
            'minecraft:weeping_vines ',
            'minecraft:tall_grass ',
            'minecraft:large_fern ',
            'minecraft:chorus_plant ',
            'minecraft:chorus_flower ',
            'minecraft:glow_lichen ',
            'minecraft:hanging_roots ',
            'minecraft:nether_wart ',
            'minecraft:lily_pad ',
            'minecraft:seagrass ',
            'minecraft:sea_pickle ',
            'minecraft:dead_tube_coral ',
            'minecraft:dead_brain_coral ',
            'minecraft:dead_bubble_coral ',
            'minecraft:dead_fire_coral ',
            'minecraft:dead_horn_coral ',
            'minecraft:tube_coral_fan ',
            'minecraft:brain_coral_fan ',
            'minecraft:bubble_coral_fan ',
            'minecraft:fire_coral_fan ',
            'minecraft:horn_coral_fan ',
            'minecraft:dead_tube_coral_fan ',
            'minecraft:dead_brain_coral_fan ',
            'minecraft:dead_bubble_coral_fan ',
            'minecraft:dead_fire_coral_fan ',
            'minecraft:dead_horn_coral_fan ',
            'minecraft:melon ',
            'minecraft:pumpkin',
            'minecraft:wheat ',
            'botania:fertilizer ',
            'botania:grass_seeds ',
            'botania:podzol_seeds ',
            'botania:mycelium_seeds ',
            'botania:dry_seeds ',
            'botania:golden_seeds ',
            'botania:vivid_seeds ',
            'botania:scorched_seeds ',
            'botania:infused_seeds ',
            'botania:mutated_seeds ',
            'botania:world_seed ',
            'botania:keep_ivy ',
            'twilightforest:moss_patch ',
            'twilightforest:brown_thorns ',
            'twilightforest:green_thorns ',
            'wizards_reborn:petals ',
            'wizards_reborn:underground_grape_vine ',
            'wizards_reborn:underground_grape ',
            'wizards_reborn:arcane_linen ',
            'wizards_reborn:pitcher_turnip ',
            'wizards_reborn:shiny_clover_seed ',
            'wizards_reborn:ground_brown_mushroom ',
            'wizards_reborn:ground_red_mushroom ',
            'wizards_reborn:ground_crimson_fungus ',
            'wizards_reborn:ground_warped_fungus ',
            'wizards_reborn:ground_mor ',
            'wizards_reborn:ground_elder_mor'
        ];
        tags.add('forge:plants', plants);

        //Making a Magical Items Tag
        let magicItems = [
            "botania:mana_pool",
            "botania:diluted_pool",
            "botania:fabulous_pool",
            "botania:alchemy_catalyst",
            "botania:conjuration_catalyst",
            "botania:manasteel_block",
            "botania:mana_diamond_block",
            "botania:mana_glass",
            "botania:runic_altar",
            'botania:mana_pylon',
            'botania:mana_distributor',
            'botania:mana_void',
            'botania:mana_detector',
            'botania:mana_fluxfield',
            'botania:prism',
            'botania:pump',
            'botania:mana_glass_pane',
            'botania:lexicon',
            'botania:white_petal',
            'botania:orange_petal',
            'botania:light_blue_petal',
            'botania:magenta_petal',
            'botania:yellow_petal',
            'botania:lime_petal',
            'botania:pink_petal',
            'botania:gray_petal',
            'botania:light_gray_petal',
            'botania:cyan_petal',
            'botania:purple_petal',
            'botania:blue_petal',
            'botania:brown_petal',
            'botania:green_petal',
            'botania:red_petal',
            'botania:black_petal',
            'botania:manasteel_ingot',
            'botania:mana_pearl',
            'botania:mana_diamond',
            'botania:mana_string',
            'botania:manasteel_nugget',
            'botania:manaweave_cloth',
            'botania:mana_powder',
            'botania:quartz_dark',
            'botania:quartz_mana',
            'botania:quartz_blaze',
            'botania:quartz_lavender',
            'botania:quartz_red',
            'botania:quartz_elven',
            'botania:quartz_sunny',
            'botania:lens_normal',
            'botania:lens_speed',
            'botania:lens_power',
            'botania:lens_time',
            'botania:lens_efficiency',
            'botania:lens_bounce',
            'botania:lens_gravity',
            'botania:lens_mine',
            'botania:lens_damage',
            'botania:lens_phantom',
            'botania:lens_magnet',
            'botania:lens_explosive',
            'botania:lens_influence',
            'botania:lens_weight',
            'botania:lens_paint',
            'botania:lens_fire',
            'botania:lens_piston',
            'botania:lens_light',
            'botania:lens_warp',
            'botania:lens_redirect',
            'botania:lens_firework',
            'botania:lens_flare',
            'botania:lens_messenger',
            'botania:lens_tripwire',
            'botania:lens_storm',
            'botania:rune_water',
            'botania:rune_fire',
            'botania:rune_earth',
            'botania:rune_air',
            'botania:rune_spring',
            'botania:rune_summer',
            'botania:rune_autumn',
            'botania:rune_winter',
            'botania:rune_mana',
            'botania:rune_lust',
            'botania:rune_gluttony',
            'botania:rune_greed',
            'botania:rune_sloth',
            'botania:rune_wrath',
            'botania:rune_envy',
            'botania:rune_pride',
            'enderstorage:ender_chest',
            'enderstorage:ender_tank',
            'endertanks:ender_tank',
            'endertanks:ender_bucket',
            'enderstorage:ender_pouch',
            'irons_spellbooks:mana_ring',
            'irons_spellbooks:silver_ring',
            'irons_spellbooks:cooldown_ring',
            'irons_spellbooks:cast_time_ring',
            'irons_spellbooks:heavy_chain_necklace',
            'irons_spellbooks:emerald_stoneplate_ring',
            'irons_spellbooks:fireward_ring',
            'irons_spellbooks:frostward_ring',
            'irons_spellbooks:poisonward_ring',
            'irons_spellbooks:conjurers_talisman',
            'irons_spellbooks:affinity_ring',
            'irons_spellbooks:concentration_amulet',
            'irons_spellbooks:amethyst_resonance_charm',
            'irons_spellbooks:invisibility_ring',
            'irons_spellbooks:arcane_essence',
            'irons_spellbooks:magic_cloth',
            'irons_spellbooks:ruined_book',
            'irons_spellbooks:arcane_salvage',
            'irons_spellbooks:arcane_ingot',
            'irons_spellbooks:ancient_knowledge_fragment',
            'irons_spellbooks:permafrost_shard',
            'irons_spellbooks:energized_core',
            'irons_spellbooks:blank_rune',
            'irons_spellbooks:fire_rune',
            'irons_spellbooks:ice_rune',
            'irons_spellbooks:lightning_rune',
            'irons_spellbooks:ender_rune',
            'irons_spellbooks:holy_rune',
            'irons_spellbooks:blood_rune',
            'irons_spellbooks:evocation_rune',
            'irons_spellbooks:arcane_rune',
            'irons_spellbooks:cooldown_rune',
            'irons_spellbooks:protection_rune',
            'irons_spellbooks:nature_rune',
            'projecte:low_covalence_dust',
            'projecte:medium_covalence_dust',
            'projecte:high_covalence_dust',
            'twilightforest:borer_essence',
            'twilightforest:carminite',
            'twilightforest:transformation_powder',
            'twilightforest:magic_beans',
            'twilightforest:fiery_blood',
            'twilightforest:fiery_tears',
            'twilightforest:fiery_ingot',
            'twilightforest:steeleaf_ingot',
            'twilightforest:naga_scale',
            'torchmaster:megatorch',
            'torchmaster:dreadlamp',
            'torchmaster:feral_flare_lantern',
            'botania:mana_tablet',
            'botania:mana_mirror',
            'botania:spell_cloth',
            'botania:black_lotus',
            'botania:blacker_lotus',
            'simplyswords:runic_tablet',
            'simplyswords:runefused_gem',
            'simplyswords:netherfused_gem',
            'simplyswords:empowered_remnant',
            'wizards_reborn:arcanum_amulet',
            'wizards_reborn:arcanum_ring',
            'wizards_reborn:arcacite_amulet',
            'wizards_reborn:arcacite_ring',
            'wizards_reborn:wissen_keychain',
            'wizards_reborn:wissen_ring',
            'unstable:soul_fragment',
            'unstable:division_sigil',
            'unstable:division_sigil_activated',
            'unstable:division_sigil_stable',
            'forbidden_arcanus:arcane_crystal',
            'forbidden_arcanus:corrupted_arcane_crystal',
            'forbidden_arcanus:arcane_crystal_dust',
            'forbidden_arcanus:mundabitur_dust',
            'forbidden_arcanus:corrupti_dust',
            'forbidden_arcanus:soul',
            'forbidden_arcanus:corrupt_soul',
            'forbidden_arcanus:enchanted_soul',
            'forbidden_arcanus:pixie',
            'forbidden_arcanus:corrupted_pixie',
            'forbidden_arcanus:rune',
            'forbidden_arcanus:dark_rune',
            'forbidden_arcanus:cloth',
            'forbidden_arcanus:crescent_moon',
            'forbidden_arcanus:crimson_stone',
            'forbidden_arcanus:soul_crimson_stone',
            'forbidden_arcanus:sanity_meter',
            'forbidden_arcanus:terrastomp_prism',
            'forbidden_arcanus:sea_prism',
            'forbidden_arcanus:whirlwind_prism',
            'forbidden_arcanus:smelter_prism',
            'forbidden_arcanus:eternal_obsidian_skull',
            'forbidden_arcanus:aureal_bottle',
            'forbidden_arcanus:splash_aureal_bottle',
            'forbidden_arcanus:arcane_crystal_dust_speck',
            'forbidden_arcanus:arcane_bone_meal',
            'forbidden_arcanus:stellarite_piece',
            'forbidden_arcanus:dark_nether_star',
            'forbidden_arcanus:arcane_crystal_obelisk',
            'forbidden_arcanus:corrupted_arcane_crystal_obelisk',
            'minecraft:end_crystal',
            'minecraft:beacon',
            'minecraft:ender_pearl',
            'minecraft:ender_eye',
            'minecraft:respawn_anchor',
            'minecraft:enchanting_table',
            'botania:dirt_rod',
            'botania:skydirt_rod',
            'botania:terraform_rod',
            'botania:cobble_rod',
            'botania:water_rod',
            'botania:tornado_rod',
            'botania:fire_rod',
            'botania:divining_rod',
            'botania:smelt_rod',
            'botania:exchange_rod',
            'botania:rainbow_rod',
            'botania:gravity_rod',
            'botania:missile_rod',
            'botania:crafting_halo',
            'botania:auto_crafting_halo',
            'botania:black_hole_talisman',
            'botania:temperance_stone',
            'botania:water_bowl',
            'botania:cacophonium',
            'botania:sextant',
            'botania:astrolabe',
            'botania:mana_ring',
            'botania:mana_ring_greater',
            'botania:aura_ring',
            'botania:aura_ring_greater',
            'botania:magnet_ring',
            'botania:magnet_ring_greater',
            'botania:water_ring',
            'botania:swap_ring',
            'botania:dodge_ring',
            'botania:mining_ring',
            'botania:pixie_ring',
            'botania:reach_ring',
            'botania:travel_belt',
            'botania:super_travel_belt',
            'botania:speed_up_belt',
            'botania:knockback_belt',
            'botania:ice_pendant',
            'botania:lava_pendant',
            'botania:super_lava_pendant',
            'botania:cloud_pendant',
            'botania:super_cloud_pendant',
            'botania:holy_cloak',
            'botania:unholy_cloak',
            'botania:balance_cloak',
            'botania:invisibility_cloak',
            'botania:third_eye',
            'botania:monocle',
            'botania:goddess_charm',
            'botania:diva_charm',
            'botania:itemfinder',
            'botania:flight_tiara',
            'botania:mana_cookie',
            'botania:mana_bottle',
            'botania:laputa_shard',
            'botania:spark',
            'botania:corporea_spark',
            'botania:corporea_spark_master',
            'irons_spellbooks:graybeard_staff',
            'irons_spellbooks:blood_staff',
            'irons_spellbooks:ice_staff',
            'irons_spellbooks:artificer_cane',
            'irons_spellbooks:lightning_rod',
            'irons_spellbooks:hither_thither_wand',
            'irons_spellbooks:emerald_stoneplate_ring'
        ]
        tags.add('forge:magicitems', magicItems)

        tags.add('forge:ingots/arcanegold', 'gtceu:arcanegold_ingot')
    }
)

ServerEvents.recipes(
    event => {
        event.replaceInput(
            {input: 'botania:manasteel_ingot'},
            'botania:manasteel_ingot',
            '#forge:ingots/manasteel'
        );
    }
)