//priority: 9253

CustomMultiblock(
    event => {
        event.create('create_combustion_engine', 'multiblock', Tier('MV'), Tier('hv'), Tier('ev'))
        .recipeType('create_combustion_engine')
        .rotationState(RotationState.NON_Y_AXIS)
        .appearanceBlock(GTBlocks.CASING_STEEL_SOLID)
        .pattern(definition => FactoryBlockPattern.start()
            .aisle('FFF', 'BBB', 'BBB')
            .aisle('FFF', 'BPB', 'BBB')
            .aisle('FFF', 'BBB', 'BBB')
            .aisle('.S.', '...', '...')
            .aisle('SCS', '.S.', '...')
            .where('F', Predicates.blocks(GTBlocks.FIREBOX_BRONZE.get())
                        .or(Predicates.autoAbilities(definition.getRecipeTypes())))
            .where('B', Predicates.blocks(GTBlocks.CASING_BRONZE_BRICKS.get())
                        .or(Predicates.abilities(PartAbility.OUTPUT_KINETIC).setExactLimit(3)))
            .where('P', Predicates.blocks(GTBlocks.CASING_BRONZE_PIPE.get()))
            .where('S', Predicates.blocks(GTBlocks.CASING_STEEL_SOLID.get()))
            .where('C', Predicates.controller(Predicates.blocks(definition.get())))
            .where('.', Predicates.any())
            .build()
        )
//        .shapeInfo(controller => MultiblockShapeInfo.builder()
//            .aisle('FFF', 'KKK', 'KKK')
//            .aisle('IFF', 'BPB', 'BBB')
//            .aisle('FFF', 'BBB', 'BBB')
//            .aisle('.S.', '...', '...')
//            .aisle('SCS', '.S.', '...')
//            .where('F', GTBlocks.FIREBOX_BRONZE.get())
//            .where('B', GTBlocks.BRONZE_HULL.get())
//            .where('P', GTBlocks.CASING_BRONZE_PIPE.get())
//            .where('S', GTBlocks.CASING_STEEL_SOLID.get())
//            .where('C', controller, Direction.SOUTH)
//            .where('.', Block.getBlock('minecraft:air'))
//            .where('K', GTMachines.OUTPUT_KINETIC, Direction.NORTH)
//            .where('I', GTMachines.ITEM_IMPORT_BUS, Direction.WEST)
//            .build()
//        )
        .workableCasingModel("gtceu:block/casings/solid/machine_casing_bronze_plated_bricks", "gtceu:block/multiblock/blast_furnace")
    }
)