CustomMultiblock(
    event => {
        event.create('extreme_embers_boiler', 'multiblock', Tier('mv'), Tier('iv'))
        .recipeType('extreme_embers_boiler')
        .rotationState(RotationState.NON_Y_AXIS)
        .appearanceBlock(() => Block.getBlock("embers:block/caminite_large_tile"))
        //.appearanceBlock(GTBlocks.CASING_BRONZE_BRICKS)
        .pattern(
            definition => FactoryBlockPattern.start()
            .aisle('-----LLL-----', '-----LLL-----', '-----L-L-----', '-----L-L-----', '-------------', '-------------', '-------------', '-------------', '-------------')
            .aisle('---BFLLLFB---', '---BL---LB---', '----L---L----', '-------------', '-------------', '-------------', '-------------', '-------------', '-------------')
            .aisle('--BLLTTTLLB--', '--B--C-C--B--', '--B--CCC--B--', '-----C-C-----', '-----C-C-----', '-----C-C-----', '-----CCC-----', '-----C-C-----', '-----S-S-----')
            .aisle('-BLTTLLLTTLB-', '-B-C-----C-B-', '---C-----C---', '---C-----C---', '---C-----C---', '---C-----C---', '---C-----C---', '---C-----C---', '---S-S-S-S---')
            .aisle('-FLTLLLLLTLF-', '-L---------L-', '-L---------L-', '-----GGG-----', '-----GGG-----', '-----GGG ----', '-------------', '-------------', '----S-S-S----')
            .aisle('LLTLLLLLLLTLL', 'L-C---S---C-L', 'L-C--GGG--C-L', 'L-C-GWWWG-C-L', '--C-GWWWG-C--', '--C-GWWWG-C--', '--C--GGG--C--', '--C---S---C--', '--SS-SOS-SS--')
            .aisle('LLTLLLLLLLTLL', 'L----SPS----L', '--C--GPG--C--', '----GWWWG----', '----GWWWG----', '----GWWWG----', '--C--GPG--C--', '-----SPS-----', '----SOOOS----')
            .aisle('LLTLLLLLLLTLL', 'L-C---S---C-L', 'L-C--GGG--C-L', 'L-C-GWWWG-C-L', '--C-GWWWG-C--', '--C-GWWWG-C--', '--C--GGG--C--', '--C---S---C--', '--SS-SOS-SS--')
            .aisle('-FLTLLLLLTLF-', '-L---------L-', '-L---------L-', '-----GGG-----', '-----GGG-----', '-----GGG-----', '-------------', '-------------', '----S-S-S----')
            .aisle('-BLTTLLLTTLB-', '-B-C-----C-B-', '---C-----C---', '---C-----C---', '---C-----C---', '---C-----C---', '---C-----C---', '---C-----C---', '---S-S-S-S --')
            .aisle('--BLLTTTLLB--', '--B--C-C--B--', '--B--CCC--B--', '-----C C-----', '-----C-C-----', '-----C-C-----', '-----CCC-----', '-----C-C-----', '-----S-S-----')
            .aisle('---BFLLLFB---', '---BL---LB---', '----L---L----', '-------------', '-------------', '-------------', '-------------', '-------------', '-------------')
            .aisle('-----LLL-----', '-----LAL-----', '-----L-L-----', '-----L-L-----', '-------------', '-------------', '-------------', '-------------', '-------------')
            .where('A', Predicates.controller(Predicates.blocks(definition.get())))
            .where('L', Predicates.blocks('embers:caminite_large_bricks'))
            .where('T', Predicates.blocks('embers:caminite_large_tile').or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setMinGlobalLimited(1).setMaxGlobalLimited(4)))
            .where('B', Predicates.blocks(GTBlocks.CASING_BRONZE_BRICKS.get()))
            .where('S', Predicates.blocks('embers:caminite_bricks'))
            .where('G', Predicates.blocks('xycraft_world:glass_viewer'))
            .where('W', Predicates.fluids('minecraft:water'))
            .where('P', Predicates.blocks(GTBlocks.CASING_STEEL_PIPE.get()))
            .where('F', Predicates.blocks('embers:caminite_large_tile').or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setMinGlobalLimited(1).setMaxGlobalLimited(8)))
            .where('C', Predicates.blocks('minecraft:copper_block').or(Predicates.blocks('minecraft:exposed_copper')).or(Predicates.blocks('minecraft:weathered_copper')).or(Predicates.blocks('minecraft:oxidized_copper')))
            .where('O', Predicates.blocks('embers:caminite_bricks').or(Predicates.abilities(PartAbility.EXPORT_FLUIDS).setMinGlobalLimited(1).setMaxGlobalLimited(5)))
            .where('-', Predicates.any())
            .build()
        )
        .workableCasingModel("gtceu:block/casings/solid/machine_casing_bronze_plated_bricks", "gtceu:block/multiblock/fusion_reactor")
    }
)